# Generated by Django 6.0.6 on 2026-07-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_created_at_user_is_active_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employer', 'Employer'), ('Candidate', 'Candidate')], default='Candidate', max_length=20),
        ),
    ]
